version: '2'

services:

  nginx:
    extends:
      file: nginx/nginx.yml
      service: nginx
    networks:
      - vitmarketcatalog

  postgres:
    extends:
      file: postgres/postgres.yml
      service: postgres
    depends_on:
      - nginx
    volumes:
      - psql-volume:/var/lib/postgresql/data
    networks:
      - vitmarketcatalog

  backend:
    extends:
      file: kotlin/kotlin.yml
      service: backend
    volumes:
      - backend-volume:/app/
    depends_on:
      - postgres
    networks:
      - vitmarketcatalog

networks:
  vitmarketcatalog:
    driver: bridge

volumes:
  backend-volume:
  psql-volume: