spring:
  datasource:
    url: jdbc:h2:mem:catalog
    driver-class-name: org.h2.Driver
    username: dev
    password: dev
    platform: h2

    initialization-mode: never

    tomcat:
      initial-size: 1000
      max-wait: 20000
      max-active: 100
      max-age: 50
      max-idle: 25
      default-auto-commit: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true

  profiles:
    active: dev

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
