spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:h2:file:~/database;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: dev
    password: dev

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
