spring:
  datasource:
    url: jdbc:h2:file:~/catalog
    driver-class-name: org.h2.Driver
    username: dev
    password: dev
    platform: h2
    data: classpath:data.sql
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  h2:
    console:
      enabled: true

  profiles:
    active: dev
