spring:
  profiles:
    active: local

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marketcatalog
    username: marketcatalog
    password: 5beeb33935c448a2828a3a043a4be7f4

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
